//! shell 补全子命令族（迭代20 M58）：`roxid completion bash|zsh|fish`
//! stdout 输出 shim 脚本（供 eval/source 或管道），`roxid completion
//! install` 自动探测 `$SHELL` 落位标准补全目录——「装完重开终端直接 TAB」
//! 体验（裁决 2026-09-09 21:29）。
//!
//! shim 为薄脚本（各 < 25 行）：仅把光标上下文转交 `roxid __complete`
//! （候选单一事实源见 complete.rs），不在 shell 侧复刻任何命令知识。
//! 不引 clap_complete：musl 静态单二进制零负担（计划书 1.3 裁决）。
//!
//! 落位路径：
//! - bash → ~/.local/share/bash-completion/completions/roxid（新终端自动加载）
//! - zsh  → ~/.zfunc/_roxid（.zshrc 缺 fpath/compinit 时追加，带标记幂等）
//! - fish → ~/.config/fish/completions/roxid.fish
//!
//! 修改历史：M58 新增 2026-09-09 21-50

use std::path::PathBuf;

use clap::Subcommand;

/// bash shim：COMP_WORDS 转交 __complete；COMP_WORDBREAKS 去 ':' 防
/// 模型名 model:tag 在冒号后断词（bash 默认把 : 当词界，补全 tag 段断裂）
const SHIM_BASH: &str = r#"# roxid completion (bash) -- generated by `roxid completion bash`
_roxid() {
    COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"
    local -a args
    args=("${COMP_WORDS[@]:1:COMP_CWORD}")
    COMPREPLY=($(compgen -W "$(roxid __complete ${args[@]+"${args[@]}"} 2>/dev/null)" -- "$cur"))
}
complete -F _roxid -o default roxid
"#;

/// zsh shim：words[2,CURRENT]（到光标的 token，不含命令名）转交 __complete；
/// 候选按行分割进 compadd（zsh 自行做前缀过滤）
const SHIM_ZSH: &str = r#"# roxid completion (zsh) -- generated by `roxid completion zsh`
_roxid() {
    local -a args cands
    args=("${(@)words[2,CURRENT]}")
    cands=(${(f)"$(roxid __complete ${args[@]} 2>/dev/null)"})
    (( ${#cands[@]} )) && compadd -a cands
}
compdef _roxid roxid
"#;

/// fish shim：commandline -cop 输出到光标的 token 列表（不含命令名）
const SHIM_FISH: &str = r#"# roxid completion (fish) -- generated by `roxid completion fish`
complete -c roxid -f -a '(roxid __complete (commandline -cop))'
"#;

/// zsh 激活行组（追加到 .zshrc；首行标记用于幂等判定与用户识别卸载）
const ZSHRC_ACTIVATE_BLOCK: &str =
    "# roxid completion\nfpath=(~/.zfunc $fpath)\nautoload -Uz compinit && compinit\n";

/// completion 子命令族
#[derive(Subcommand)]
pub enum CompletionCmd {
    /// Print the bash completion script
    Bash,
    /// Print the zsh completion script
    Zsh,
    /// Print the fish completion script
    Fish,
    /// Install completion into the standard directory (new terminal)
    Install,
}

/// `completion` 子命令入口（本地操作，不经 serve）
///
/// - 参数 cmd：completion 二级子命令
/// - 返回：进程退出码
pub fn cmd_completion(cmd: CompletionCmd) -> i32 {
    match cmd {
        CompletionCmd::Bash => {
            print!("{SHIM_BASH}");
            0
        }
        CompletionCmd::Zsh => {
            print!("{SHIM_ZSH}");
            0
        }
        CompletionCmd::Fish => {
            print!("{SHIM_FISH}");
            0
        }
        CompletionCmd::Install => match install_completion(None) {
            Ok(msg) => {
                println!("{msg}");
                0
            }
            Err(e) => {
                eprintln!("{e}");
                1
            }
        },
    }
}

/// 安装补全到标准目录（setup 首次引导默认顺带调用同一内核）。
/// 幂等：重跑覆盖脚本；zsh 激活块按标记行去重。
///
/// - 参数 explicit_shell：显式指定的 shell 名（当前 None——探测 $SHELL；
///   预留扩展位，调用方可传 "bash"/"zsh"/"fish"）
/// - 返回：Ok(成功提示文本)；Err(失败原因)
pub fn install_completion(explicit_shell: Option<&str>) -> Result<String, String> {
    let shell = match explicit_shell.map(str::to_string).or_else(detect_shell) {
        Some(s) => s,
        None => return Err(unknown_shell_hint()),
    };
    let home = home_dir().ok_or_else(|| "无法确定用户主目录（$HOME 未设置）".to_string())?;
    match shell.as_str() {
        "bash" => {
            let path = home
                .join(".local/share/bash-completion/completions")
                .join("roxid");
            write_script(&path, SHIM_BASH)?;
            Ok(format!(
                "bash 补全已安装：{}\n重开终端即可 TAB 补全",
                path.display()
            ))
        }
        "zsh" => {
            let path = home.join(".zfunc").join("_roxid");
            write_script(&path, SHIM_ZSH)?;
            ensure_zshrc_activation(&home)?;
            Ok(format!(
                "zsh 补全已安装：{}\n重开终端即可 TAB 补全",
                path.display()
            ))
        }
        "fish" => {
            let path = home.join(".config/fish/completions").join("roxid.fish");
            write_script(&path, SHIM_FISH)?;
            Ok(format!(
                "fish 补全已安装：{}\n重开终端即可 TAB 补全",
                path.display()
            ))
        }
        other => Err(format!("不支持的 shell：{other}（支持 bash / zsh / fish）")),
    }
}

/// 探测当前 shell（$SHELL basename）
fn detect_shell() -> Option<String> {
    std::env::var("SHELL")
        .ok()
        .and_then(|s| {
            std::path::Path::new(&s)
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
        })
        .filter(|name| matches!(name.as_str(), "bash" | "zsh" | "fish"))
}

/// $SHELL 无法识别时的提示文案（install 非交互兜底：手动三选一执行）
fn unknown_shell_hint() -> String {
    "无法识别当前 shell（$SHELL 未设置或不支持）。请手动执行其一：\n  \
        roxid completion bash >> ~/.bashrc\n  \
        roxid completion zsh >> ~/.zshrc\n  \
        roxid completion fish > ~/.config/fish/completions/roxid.fish"
        .to_string()
}

/// 用户主目录（$HOME；无 dirs 依赖，遵循零新增依赖裁决）
fn home_dir() -> Option<PathBuf> {
    std::env::var("HOME")
        .ok()
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
}

/// 写 shim 脚本（父目录按需创建；幂等覆盖）
///
/// - 参数 path：落位路径
/// - 参数 content：脚本全文
/// - 返回：io 错误转字符串说明
fn write_script(path: &std::path::Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("创建目录 {} 失败：{e}", parent.display()))?;
    }
    std::fs::write(path, content).map_err(|e| format!("写入 {} 失败：{e}", path.display()))
}

/// .zshrc 激活块保障：缺 fpath/compinit 配置时追加标记块（含幂等判定——
/// 已含 `# roxid completion` 标记行则跳过，重复执行零重复追加）
///
/// - 参数 home：用户主目录
/// - 返回：io 错误转字符串说明
fn ensure_zshrc_activation(home: &std::path::Path) -> Result<(), String> {
    let zshrc = home.join(".zshrc");
    let existing = std::fs::read_to_string(&zshrc).unwrap_or_default();
    if existing.contains("# roxid completion") || existing.contains("fpath=(~/.zfunc") {
        return Ok(()); // 已有激活配置（本工具或用户手工），不重复追加
    }
    let mut next = existing;
    if !next.is_empty() && !next.ends_with('\n') {
        next.push('\n');
    }
    next.push_str(ZSHRC_ACTIVATE_BLOCK);
    std::fs::write(&zshrc, next).map_err(|e| format!("写入 {} 失败：{e}", zshrc.display()))
}

/// 补全安装一步（setup 向导调用）：失败不中断引导，仅提示
pub fn install_step_for_wizard() {
    match install_completion(None) {
        Ok(msg) => println!("{msg}"),
        Err(e) => eprintln!("补全安装跳过：{e}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// HOME 沙箱串行锁（std::env::set_var 全局态，防测试并行互踩）
    static HOME_LOCK: Mutex<()> = Mutex::new(());

    /// 三系 shim 模板形态断言（注册行是 shell 识别的关键字）
    #[test]
    fn shim_templates_register_completion() {
        assert!(SHIM_BASH.contains("complete -F _roxid"));
        assert!(SHIM_BASH.contains("roxid __complete"));
        assert!(SHIM_ZSH.contains("compdef _roxid"));
        assert!(SHIM_ZSH.contains("roxid __complete"));
        assert!(SHIM_FISH.contains("complete -c roxid"));
        assert!(SHIM_FISH.contains("roxid __complete"));
        // bash 词界修正存在（模型名 model:tag 冒号断词防护）
        assert!(SHIM_BASH.contains("COMP_WORDBREAKS"));
    }

    /// HOME 沙箱：三 shell 显式落位 + 内容正确 + 幂等重跑不炸
    #[test]
    fn install_explicit_shells_land_and_idempotent() {
        let _guard = HOME_LOCK.lock().unwrap();
        let sandbox = std::env::temp_dir().join(format!("roxid-completion-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&sandbox);
        std::fs::create_dir_all(&sandbox).unwrap();
        let prev_home = std::env::var("HOME").unwrap_or_default();
        std::env::set_var("HOME", &sandbox);

        for (shell, expect_path) in [
            (
                "bash",
                sandbox.join(".local/share/bash-completion/completions/roxid"),
            ),
            ("zsh", sandbox.join(".zfunc/_roxid")),
            ("fish", sandbox.join(".config/fish/completions/roxid.fish")),
        ] {
            install_completion(Some(shell)).unwrap_or_else(|e| panic!("{shell} 落位失败：{e}"));
            assert!(
                expect_path.is_file(),
                "{shell} 脚本未落位：{}",
                expect_path.display()
            );
        }

        // zsh 激活块：.zshrc 被追加且仅一次（幂等）
        let zshrc = sandbox.join(".zshrc");
        let first = std::fs::read_to_string(&zshrc).unwrap();
        assert!(first.contains("# roxid completion"));
        assert_eq!(first.matches("fpath=(~/.zfunc").count(), 1);
        ensure_zshrc_activation(&sandbox).unwrap();
        let second = std::fs::read_to_string(&zshrc).unwrap();
        assert_eq!(first, second, "重跑不得重复追加激活块");

        // 幂等重跑 install 全链路（覆盖写不报错）
        install_completion(Some("bash")).unwrap();

        std::env::set_var("HOME", prev_home);
        let _ = std::fs::remove_dir_all(&sandbox);
    }

    /// .zshrc 已有用户手工 fpath 配置时不追加（尊重用户配置）
    #[test]
    fn zshrc_with_existing_fpath_untouched() {
        let _guard = HOME_LOCK.lock().unwrap();
        let sandbox = std::env::temp_dir().join(format!("roxid-zshrc-keep-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&sandbox);
        std::fs::create_dir_all(&sandbox).unwrap();
        std::fs::write(sandbox.join(".zshrc"), "fpath=(~/.zfunc $fpath)\n").unwrap();
        ensure_zshrc_activation(&sandbox).unwrap();
        let content = std::fs::read_to_string(sandbox.join(".zshrc")).unwrap();
        assert_eq!(
            content, "fpath=(~/.zfunc $fpath)\n",
            "已有 fpath 配置零追加"
        );
        let _ = std::fs::remove_dir_all(&sandbox);
    }

    /// 不支持的 shell 显式报错（不误写任何文件）
    #[test]
    fn unsupported_shell_errors() {
        let _guard = HOME_LOCK.lock().unwrap();
        let sandbox = std::env::temp_dir().join(format!("roxid-badshell-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&sandbox);
        std::fs::create_dir_all(&sandbox).unwrap();
        let prev_home = std::env::var("HOME").unwrap_or_default();
        std::env::set_var("HOME", &sandbox);
        let err = install_completion(Some("tcsh")).unwrap_err();
        assert!(err.contains("不支持的 shell"));
        assert!(
            sandbox.read_dir().unwrap().next().is_none(),
            "失败路径不落文件"
        );
        std::env::set_var("HOME", prev_home);
        let _ = std::fs::remove_dir_all(&sandbox);
    }

    /// detect_shell 的 basename 提取（探测纯函数部分经显式路径验证）
    #[test]
    fn shim_usage_note_alignment() {
        // bash -n 语法检查依赖系统 bash，改以关键行存在性断言（见上）；
        // 此处验证 ZSHRC 块以标记行开头（便于 grep 卸载）
        assert!(ZSHRC_ACTIVATE_BLOCK.starts_with("# roxid completion\n"));
    }
}
